spring:
  application:
    name: light-rag
  r2dbc:
    url: r2dbc:postgresql://localhost:15432/r1?reWriteBatchedInserts=true
    name: r1
    username: rag
    password: rag
    pool:
      validation-query: LOAD 'age';SET search_path = public,"$user",ag_catalog;
      enabled: true
      initial-size: 2
      max-size: 10
      max-acquire-time: 3s
      max-idle-time: 10m
      max-create-connection-time: 5s
      max-life-time: 30m
      max-validation-time: 2s


  liquibase:
    url: jdbc:postgresql://localhost:15432/r1
    user: rag
    password: rag
    change-log: classpath:db/changelog/master.yaml
  cache:
    cache-names: "graph_entity,graph_relation,graph_degree"
    caffeine:
      spec: "maximumSize=5000,expireAfterAccess=600s"

rag:
  storage:
    type: postgres
    workspace: default
    embedding-batch-num: 16
    graph:
      name: dickens
  llm:
    embedding:
      provider: ollama
      model: nomic-embed-text
      dimension: 768
      max-token-size: 8192
      concurrent-limit: 16
    completion:
      provider: zhipu
      api-key: ${ZHIPU_API_KEY:}
      model: glm-4-flashx
