spring:
  application:
    name: light-rag
  datasource:
    url: jdbc:postgresql://localhost:15432/r1?reWriteBatchedInserts=true
    username: rag
    password: rag
    hikari:
      auto-commit: true
      connection-timeout: 3000
      idle-timeout: 600000
      connection-test-query: select 1
      minimum-idle: 5
      maximum-pool-size: 32
      connection-init-sql: LOAD 'age';SET search_path = public,"$user",ag_catalog;
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    url: jdbc:postgresql://localhost:15432/r1
    user: rag
    password: rag
    change-log: classpath:db/changelog/master.yaml
  cache:
    cache-names: "graph_entity,graph_relation,graph_degree"
    caffeine:
      spec: "maximumSize=5000,expireAfterAccess=600s"

rag:
  storage:
    type: postgres
    workspace: default
    embedding-batch-num: 16
    graph:
      name: dickens
  llm:
    embedding:
      provider: ollama
      model: nomic-embed-text
      dimension: 768
      max-token-size: 8192
      concurrent-limit: 16
    completion:
      provider: zhipu
      api-key: ${ZHIPU_API_KEY:}
      model: glm-4-flashx
