--liquibase formatted sql
--changeset Samuel Chan:v1.0.2
--comment: add surrogate keys
alter TABLE LIGHTRAG_DOC_FULL add column surrogate_id bigserial;
alter TABLE LIGHTRAG_DOC_STATUS add column surrogate_id bigserial;
alter table LIGHTRAG_LLM_CACHE add column surrogate_id bigserial;
alter TABLE LIGHTRAG_VDB_ENTITY add column surrogate_id bigserial;
alter TABLE LIGHTRAG_VDB_RELATION add column surrogate_id bigserial;
alter table LIGHTRAG_DOC_CHUNKS add column surrogate_id bigserial;

ALTER TABLE LIGHTRAG_DOC_CHUNKS DROP CONSTRAINT LIGHTRAG_DOC_CHUNKS_MK;
ALTER TABLE LIGHTRAG_DOC_CHUNKS ADD PRIMARY KEY (surrogate_id);
CREATE UNIQUE INDEX LIGHTRAG_DOC_CHUNKS_MK ON LIGHTRAG_DOC_CHUNKS (workspace, id);

ALTER TABLE LIGHTRAG_DOC_FULL DROP CONSTRAINT LIGHTRAG_DOC_FULL_PK;
ALTER TABLE LIGHTRAG_DOC_FULL ADD PRIMARY KEY (surrogate_id);
CREATE UNIQUE INDEX LIGHTRAG_DOC_FULL_MK on LIGHTRAG_DOC_FULL (workspace, id);


ALTER TABLE LIGHTRAG_DOC_STATUS DROP CONSTRAINT LIGHTRAG_DOC_STATUS_PK;
ALTER TABLE LIGHTRAG_DOC_STATUS ADD PRIMARY KEY (surrogate_id);
CREATE UNIQUE INDEX LIGHTRAG_DOC_STATUS_MK on LIGHTRAG_DOC_STATUS(workspace, id);

ALTER TABLE LIGHTRAG_LLM_CACHE DROP CONSTRAINT LIGHTRAG_LLM_CACHE_PK;
ALTER TABLE LIGHTRAG_LLM_CACHE ADD PRIMARY KEY (surrogate_id);
CREATE UNIQUE INDEX LIGHTRAG_LLM_CACHE_MK on LIGHTRAG_LLM_CACHE(workspace, mode, id);

ALTER TABLE LIGHTRAG_VDB_ENTITY DROP CONSTRAINT LIGHTRAG_VDB_ENTITY_PK;
ALTER TABLE LIGHTRAG_VDB_ENTITY ADD PRIMARY KEY (surrogate_id);
CREATE UNIQUE INDEX LIGHTRAG_VDB_ENTITY_MK on LIGHTRAG_VDB_ENTITY(workspace, id);

ALTER TABLE LIGHTRAG_VDB_RELATION DROP CONSTRAINT LIGHTRAG_VDB_RELATION_PK;
ALTER TABLE LIGHTRAG_VDB_RELATION ADD PRIMARY KEY (surrogate_id);
CREATE UNIQUE INDEX LIGHTRAG_VDB_RELATION_MK on LIGHTRAG_VDB_RELATION(workspace, id);
--rollback;